name: Test env loading behavior

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt || pip install pytest python-dotenv

      - name: Run pytest
        run: |
          source venv/bin/activate
          pytest tests/test_env_check.py -s
